language: ruby

cache: bundler 

before_install: gem update bundler

install:
  - bundle install
  - bundle update
  - bundle update github-pages


script:
  #- "./script/build-travis.sh"
  - bundle exec jekyll build
branches:
  only:
  - main

#sudo: false
#test commit